version: '3.6'
services:
  snowplow-micro:
    image: 'snowplow/snowplow-micro:1.0.0'
    command:
      - --collector-config
      - /config/micro.conf
      - --iglu
      - /config/iglu.json
    volumes:
      - type: bind
        source: ./config
        target: /config
    ports:
      - '9090:9090'
